# Generated by Django 2.2.9 on 2020-01-25 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import printer.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'Requested'), (2, 'Printed'), (3, 'Rejected'), (4, 'Partly Paid'), (5, 'Paid')])),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('printed_on', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('is_both_sides', models.BooleanField(default=True, verbose_name='Both Sides')),
                ('is_color', models.BooleanField(default=False, verbose_name='Color')),
                ('front_page', models.IntegerField(default=0, verbose_name='Want some front pages')),
                ('blank_pages', models.IntegerField(default=0, verbose_name='Want some front pages')),
                ('no_of_bnw_Single_pages', models.IntegerField(default=0)),
                ('no_of_bnw_double_pages', models.IntegerField(default=0)),
                ('no_of_color_Single_pages', models.IntegerField(default=0)),
                ('no_of_color_double_pages', models.IntegerField(default=0)),
                ('amount_paid', models.FloatField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Print Request',
                'verbose_name_plural': 'Print Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintRequestFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to=printer.models.PrintRequestFile.print_request_file_path)),
                ('no_of_copies', models.IntegerField()),
                ('print_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.PrintRequest')),
            ],
        ),
    ]
