# Generated by Django 2.2.9 on 2020-01-27 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import printer.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('page', models.FloatField()),
                ('bnw_page', models.FloatField()),
                ('color_pages', models.FloatField()),
                ('wef', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'ordering': ['-wef'],
            },
        ),
        migrations.CreateModel(
            name='PrintRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'Requested'), (2, 'Printed'), (3, 'Rejected'), (4, 'Cancelled'), (5, 'Paid')], default=1)),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Description')),
                ('printed_on', models.DateTimeField(blank=True, null=True)),
                ('cancelled_on', models.DateTimeField(blank=True, null=True)),
                ('rejected_on', models.DateTimeField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('is_both_side', models.BooleanField(default=True, verbose_name='Both Sides')),
                ('is_color', models.BooleanField(default=False, verbose_name='Color')),
                ('no_of_front_page', models.PositiveIntegerField(default=0, verbose_name='Want some front pages')),
                ('no_of_blank_page', models.PositiveIntegerField(default=0, verbose_name='Want some blank pages')),
                ('no_of_page', models.PositiveIntegerField(default=0)),
                ('no_of_bnw_page', models.PositiveIntegerField(default=0)),
                ('no_of_color_page', models.PositiveIntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Print Request',
                'verbose_name_plural': 'Print Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintRequestFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document', models.FileField(null=True, upload_to=printer.models.PrintRequestFile.print_request_file_path)),
                ('no_of_copies', models.PositiveIntegerField(default=0)),
                ('print_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.PrintRequest')),
            ],
            options={
                'verbose_name': 'Print Request File',
                'verbose_name_plural': 'Print Requests Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
